name: PR

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - uses: Swatinem/rust-cache@v1

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-07-26
        components: rustfmt, clippy

    - name: checks

    - run: cargo +nightly-2021-07-26 test --workspace
    - run: cargo +nightly-2021-07-26 fmt -- --check

    - name: clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features -- -D warnings

  test-osx:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-26
          components: rustfmt, clippy

      - run: cargo +nightly-2021-07-26 test --workspace

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-26
          components: rustfmt, clippy

      - run: cargo +nightly-2021-07-26 test --workspace
